#!/bin/sh -e
# Cron-apt postrm script using debconf
# Written by Ola Lundqvist <opal@debian.org>

case "$1" in
    purge)
        if [ -d /var/log/cron-apt ] ; then
	    rm -Rf /var/log/cron-apt
	fi
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    
    ;;
    
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

#DEBHELPER#

exit 0
