#!/bin/sh -e
# Kt-update postrm script using debconf

case "$1" in
    purge)
        if [ -d /var/log/kt-update ] ; then
		rm -Rf /var/log/kt-update
		rm -Rf /var/lib/kt-update
		rm -f /etc/apt/sources.list.d/kt-media.list /etc/apt/sources.list.d/kt-remote.list
	fi
    ;;

    upgrade)
    ;;

    remove|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
    
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

#DEBHELPER#

exit 0
